name: flexus_framework
description: Flexus Framework
version: 4.0.58+23
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Development
  get: ^4.6.1
  flutter_flavor: ^3.0.3
  intl: ^0.17.0
  logger: ^1.1.0
  collection: ^1.15.0
  network_to_file_image: ^3.1.0
  path_provider: ^2.0.8
  device_preview: ^1.0.0
  package_info_plus: ^1.3.0


  #UI
  carousel_slider: ^4.0.0
  google_fonts: ^2.2.0
  font_awesome_flutter: ^9.2.0

  loading_overlay: ^0.3.0
  visibility_detector: ^0.2.2
  focus_detector: ^2.0.1
  image_picker: ^0.8.4+6
  image_cropper: ^1.4.1
  sizer: ^2.0.15

  #Form:
  flutter_form_builder: ^7.1.0
  form_builder_validators: ^7.4.0

  #Firebase
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.6
  firebase_analytics: ^9.1.0

  #Auth
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1
  sign_in_with_apple: ^3.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
